// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  // 帮助中心侧边栏
  helpSidebar: [
    {
      type: 'autogenerated',
      dirName: 'help',
    },
  ],
  // 新闻中心侧边栏
  newsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'news',
    },
  ],
  // 文章中心侧边栏
  articleSidebar: [
    {
      type: 'autogenerated',
      dirName: 'article',
    },
  ],
  // 活动中心侧边栏
  activitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'activity',
    },
  ],
  // 校园中心侧边栏
  campusSidebar: [
    {
      type: 'autogenerated',
      dirName: 'campus',
    },
  ],
  // 科技中心侧边栏
  technologySidebar: [
    {
      type: 'autogenerated',
      dirName: 'technology',
    },
  ],
  // 竞赛中心侧边栏
  contestSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contest',
    },
  ],
  // 校友中心侧边栏
  alumniSidebar: [
    {
      type: 'autogenerated',
      dirName: 'alumni',
    },
  ],
};

export default sidebars;
